### ISSUE TITLE
Training Model

### ISSUE THREAD

**Issue by elaskar** [liuzl/ling#6]
Hi liuzl, idk how to contact you, so basically my question is following your work I wonder how is it possible to train via machine learning some models to build a chatbot using ling, so if you have any advices or tips feel free to answer me on this issue or via mail on etienne.laskar74@gmail.com

**Comment by liuzl** [comment]
There is another project [FMR](https://github.com/liuzl/fmr) on github which is based on **ling**. Chatbot is one of its aims. I think FMR would be helpful for you. 

I could be reached at liang@zliu.org or zhanliangliu@gmail.com.
